### PR TITLE
Design-related changes to SOW

### PR DESCRIPTION
**Pull request by edmullen**
I have made a number of language changes related to design requirements and want to merge these into the pws-search branch.

- User research: Clarified two points about research to ensure that design research to understand needs and usability testing to assess the efficacy of proposed solutions are clear and accounted for.
- Clarified the expectations for the vendor to align with the [modular product design strategy](https://github.com/18F/acq-alaska-dhss-modernization/blob/master/modular-experience.md)
- Added a requirement aimed at calling out the need to consider geographical low speed considerations, device agnosticism, and cross-browser issues without being too prescriptive.
- Added periods where they were missing.

cc @randyhart @mtorres253

### CODE REVIEW

**Comment by randyhart** [comment]
@edmullen regarding:
`Work will be conducted in two-week sprints and reviewed at the end of each sprint for acceptability before moving on.`

We've found that some vendors that prefer working in one-week sprints in our agile BPA buys.  Leaves us with two decisions:

If it's important to us that the vendors work in two-week sprints because that's the cadence that the Alaska team is now accustomed to, we should leave this as-is.

If we're ok allowing flexibility depending on the vendors' normal approaches, we can change this to "Work will be conducted in sprints that are two weeks or less.  Work will be reviewed at the end of each sprint for acceptability before moving on`

**Comment by waldoj** [comment]
FWIW, I'm an advocate of allowing vendors flexibility on sprint durations, although I think it's unwise to have sprints habitually exceed two weeks.

**Comment by billy22g** [comment]
We've found on various projects that it's important to the greatest extent possible to allow vendors to work the way they prefer to work, with some constraints. We've used the language "sprints shall have a length of two weeks or less." 

That has worked well to allow for sprints of one week if that's the vendor's preference, but ensuring that you're avoiding Agile-fall type ~3 month sprints, for example.

**Comment by edmullen** [comment]
All good points and I agree. I was not making a statement recommending two-week sprints, I just removed the initial phrase relating to this being an Agile BPA project that seemed like a holdover from our boilerplate language. I probably should have left it alone, because I was trying to limit the scope of changes to the design matters. 

So  I agree with all these comments, but I'm also a bit hesitant to open up broader SOW matters in this PR because I wasn't involved in the prior back-and-forth. 

@randy, you've followed that thread and I'll follow you lead. Should I remove "two-week", revert to the original sentence, or leave it as is.

**Comment by randyhart** [comment]
There's a time commitment to the agile ceremonies (i.e. more grooming/planning/retro meetings, etc.) so I want to make sure Alaska's product team is good with sprints that are shorter than the 2-week cadence we're using now.   

The Alaska product owner and many on her team will need to attend most of the meetings - so I think the final call should probably be made by @monicaw2 about whether a shorter cadence would work for them.

I think we can get a final answer after a fairly short discussion this week.

**Comment by randyhart** [comment]
also - just so it doesn't get lost in the back and forth, all the other changes LGTM.

**Comment by edmullen** [comment]
@randyhart This language is in the QAP, _"The Product Team and PO, along with the product owner, will inspect all tasks required by the contract to ensure contractor compliance with the contract requirements at the conclusion of each sprint, which shall have a length of two weeks or less, unless agreed upon by the vendor and product team."_

So I agree with the point, but think I’d prefer to not address it as part of this PR. You could either do a PR on the original [pws-search branch](https://github.com/18F/acq-alaska-dhss-modernization/blob/pws-search/sow/search.md) to remove “two-week” or take note for future cross-walking. I think it muddies this PR a bit. Is that OK?

**Comment by randyhart** [comment]
Yes - that makes sense to me.  Let's flag it as something that needs to be addressed for consistency's sake in future reviews - but I don't think it should get in the way of accepting this PR.  

Like we discussed - the changes you made in this PR were more about `design` than `agile practices` - so you're right that this small issue would muddy things.  Apologies for the back and forth!

**Comment by sztaylorakgov** [comment]
I want to weigh in and make some observations about sprint length from our experiences the last several months:

1. Agile/Scrum is something that is still new for AK.  We're still working to get up on step with 2 week sprints.  
2. I believe the principle I've heard for transitioning to agile is start with longer sprints, get good and then decrease sprint duration.  
3. I understand typical starting place for orgs that are used to waterfall is something more like 4 to 6 weeks.
4. Going faster when we're not ready can lead to failure.  Not because people aren't willing, but because there is literally a different approach to breaking down work for faster sprints.
5. So, my view is that DHSS DPA and FMS staff jumped in the deep end back in Feb/Mar of this year doing two week sprints....We're always eager here in AK, plus you caught us in the light part of the year when we all wake up from hibernation and have to get everything done in flurry ;-) 
6. Thinking of one week sprints at the moment is pretty hard, especially when we consider our recent lessons in how far we have to grow our DevOps culture
7. The vendor might like to work faster, but they will not succeed if DHSS staff are not able to do our part to support and/or cannot visualize and understand the work.  I cannot over-emphasize this point: if we're not ready to work this fast, then we will not understand the deliverables coming out of the sprints.  If we don't understand the deliverables, this will lead to missed expectations and friction between the product team and the delivery team.
8. We should be realistic with our vendors and be looking for long term success in partnerships.  Instead of trying to go as fast as possible right out of the gates, let's start from where we are (2 week sprints) and then make the choice to go faster deliberately and in partnership, based on successful delivery.

**Pull request merged**
