### PR TITLE
Technical prototype page

### PR DESCRIPTION
**Pull request by mtorres253**
Created a single page to explain technical prototyping in general, as it applies to our work with Alaska, and details of the first prototype, to help clarify for the team, and others.

### CODE REVIEW

**Comment by ctro** [comment]
This seems great to me, hits all the right spots.  👍

**Comment by waldoj** [comment]
> new legacy
Great phrase.

**Comment by waldoj** [comment]
Everything here is solid. The only changes I made were fiddly copyediting things.

**Comment by randyhart** [comment]
ed's changes look good....i think this is ready to go.

**Comment by mtorres253** [comment]
@ctro can you just approve the pull request? I'll ask someone from AK to merge when you're done.

**Pull request merged**
