### PR TITLE
Product roadmap link

### PR DESCRIPTION
**Pull request by mtorres253**
Adding some descriptive text and a link to the product roadmap to be merged when ready.

### CODE REVIEW

**Comment by sztaylorakgov** [comment]
@mtorres253 I get routed to a Mural sign-in with that link to the product road map.  Is that the intention?

**Comment by mtorres253** [comment]
No @sztaylorakgov that is not the intention. Thanks for pointing that out. I'll fix.

**Comment by mtorres253** [comment]
The link does not take me to a login page when I am logged out. I just see the view of the roadmap. If it's still happening for you, @sztaylorakgov let me know

**Comment by sztaylorakgov** [comment]
@mtorres253 I logged out of Mural and the followed the link again and it worked without a problem.  Not sure what happened previously, but looks like it is working OK now!

**Pull request merged**
